# Basic set up for three package managers

version: 2
updates:
  # Maintain dependencies for Python
  # Dependabot supports updates to pyproject.toml files
  # if they follow the PEP 621 standard.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "gmuloc"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore: "
    cooldown:
      default-days: 7
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "gmuloc"
    labels:
      - "CI"
    commit-message:
      prefix: "ci: "
    cooldown:
      default-days: 7
