version: 2
updates:
  # Maintain dependencies for Python
  # Dependabot supports updates to pyproject.toml files
  # if they follow the PEP 621 standard.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "gmuloc"
      - "carlbuchmann"
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore: "
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "carlbuchmann"
      - "gmuloc"
    labels:
      - 'CI'
    commit-message:
      prefix: "ci: "
