changelog:
  exclude:
    labels:
      - 'rn: test(j2lint)'
      - 'rn: test(cli)'
      - 'rn: test(rules)'
      - 'rn: test(j2lint|cli)'
      - 'rn: test(j2lint|rules)'
      - 'rn: test(cli|j2lint)'
      - 'rn: test(cli|rules)'
      - 'rn: test(rules|j2lint)'
      - 'rn: test(rules|cli)'
      - 'rn: test(j2lint|cli|rules)'
      - 'rn: test(j2lint|rules|cli)'
      - 'rn: test(cli|j2lint|rules)'
      - 'rn: test(cli|rules|j2lint)'
      - 'rn: test(rules|j2lint|cli)'
      - 'rn: test(rules|cli|j2lint)'
      - 'rn: test'
      - 'rn: ci(j2lint)'
      - 'rn: ci(cli)'
      - 'rn: ci(rules)'
      - 'rn: ci(j2lint|cli)'
      - 'rn: ci(j2lint|rules)'
      - 'rn: ci(cli|j2lint)'
      - 'rn: ci(cli|rules)'
      - 'rn: ci(rules|j2lint)'
      - 'rn: ci(rules|cli)'
      - 'rn: ci(j2lint|cli|rules)'
      - 'rn: ci(j2lint|rules|cli)'
      - 'rn: ci(cli|j2lint|rules)'
      - 'rn: ci(cli|rules|j2lint)'
      - 'rn: ci(rules|j2lint|cli)'
      - 'rn: ci(rules|cli|j2lint)'
      - 'rn: ci'
  categories:
    - title: 'Breaking Changes'
      labels:
        - 'rn: feat(j2lint)!'
        - 'rn: feat(cli)!'
        - 'rn: feat(rules)!'
        - 'rn: feat(j2lint|cli)!'
        - 'rn: feat(j2lint|rules)!'
        - 'rn: feat(cli|j2lint)!'
        - 'rn: feat(cli|rules)!'
        - 'rn: feat(rules|j2lint)!'
        - 'rn: feat(rules|cli)!'
        - 'rn: feat(j2lint|cli|rules)!'
        - 'rn: feat(j2lint|rules|cli)!'
        - 'rn: feat(cli|j2lint|rules)!'
        - 'rn: feat(cli|rules|j2lint)!'
        - 'rn: feat(rules|j2lint|cli)!'
        - 'rn: feat(rules|cli|j2lint)!'
        - 'rn: feat!'
        - 'rn: fix(j2lint)!'
        - 'rn: fix(cli)!'
        - 'rn: fix(rules)!'
        - 'rn: fix(j2lint|cli)!'
        - 'rn: fix(j2lint|rules)!'
        - 'rn: fix(cli|j2lint)!'
        - 'rn: fix(cli|rules)!'
        - 'rn: fix(rules|j2lint)!'
        - 'rn: fix(rules|cli)!'
        - 'rn: fix(j2lint|cli|rules)!'
        - 'rn: fix(j2lint|rules|cli)!'
        - 'rn: fix(cli|j2lint|rules)!'
        - 'rn: fix(cli|rules|j2lint)!'
        - 'rn: fix(rules|j2lint|cli)!'
        - 'rn: fix(rules|cli|j2lint)!'
        - 'rn: fix!'
        - 'rn: cut(j2lint)!'
        - 'rn: cut(cli)!'
        - 'rn: cut(rules)!'
        - 'rn: cut(j2lint|cli)!'
        - 'rn: cut(j2lint|rules)!'
        - 'rn: cut(cli|j2lint)!'
        - 'rn: cut(cli|rules)!'
        - 'rn: cut(rules|j2lint)!'
        - 'rn: cut(rules|cli)!'
        - 'rn: cut(j2lint|cli|rules)!'
        - 'rn: cut(j2lint|rules|cli)!'
        - 'rn: cut(cli|j2lint|rules)!'
        - 'rn: cut(cli|rules|j2lint)!'
        - 'rn: cut(rules|j2lint|cli)!'
        - 'rn: cut(rules|cli|j2lint)!'
        - 'rn: cut!'
        - 'rn: revert(j2lint)!'
        - 'rn: revert(cli)!'
        - 'rn: revert(rules)!'
        - 'rn: revert(j2lint|cli)!'
        - 'rn: revert(j2lint|rules)!'
        - 'rn: revert(cli|j2lint)!'
        - 'rn: revert(cli|rules)!'
        - 'rn: revert(rules|j2lint)!'
        - 'rn: revert(rules|cli)!'
        - 'rn: revert(j2lint|cli|rules)!'
        - 'rn: revert(j2lint|rules|cli)!'
        - 'rn: revert(cli|j2lint|rules)!'
        - 'rn: revert(cli|rules|j2lint)!'
        - 'rn: revert(rules|j2lint|cli)!'
        - 'rn: revert(rules|cli|j2lint)!'
        - 'rn: revert!'
        - 'rn: refactor(j2lint)!'
        - 'rn: refactor(cli)!'
        - 'rn: refactor(rules)!'
        - 'rn: refactor(j2lint|cli)!'
        - 'rn: refactor(j2lint|rules)!'
        - 'rn: refactor(cli|j2lint)!'
        - 'rn: refactor(cli|rules)!'
        - 'rn: refactor(rules|j2lint)!'
        - 'rn: refactor(rules|cli)!'
        - 'rn: refactor(j2lint|cli|rules)!'
        - 'rn: refactor(j2lint|rules|cli)!'
        - 'rn: refactor(cli|j2lint|rules)!'
        - 'rn: refactor(cli|rules|j2lint)!'
        - 'rn: refactor(rules|j2lint|cli)!'
        - 'rn: refactor(rules|cli|j2lint)!'
        - 'rn: refactor!'
        - 'rn: bump(j2lint)!'
        - 'rn: bump(cli)!'
        - 'rn: bump(rules)!'
        - 'rn: bump(j2lint|cli)!'
        - 'rn: bump(j2lint|rules)!'
        - 'rn: bump(cli|j2lint)!'
        - 'rn: bump(cli|rules)!'
        - 'rn: bump(rules|j2lint)!'
        - 'rn: bump(rules|cli)!'
        - 'rn: bump(j2lint|cli|rules)!'
        - 'rn: bump(j2lint|rules|cli)!'
        - 'rn: bump(cli|j2lint|rules)!'
        - 'rn: bump(cli|rules|j2lint)!'
        - 'rn: bump(rules|j2lint|cli)!'
        - 'rn: bump(rules|cli|j2lint)!'
        - 'rn: bump!'
    - title: 'New features and enhancements'
      labels:
        - 'rn: feat(j2lint)'
        - 'rn: feat(cli)'
        - 'rn: feat(rules)'
        - 'rn: feat(j2lint|cli)'
        - 'rn: feat(j2lint|rules)'
        - 'rn: feat(cli|j2lint)'
        - 'rn: feat(cli|rules)'
        - 'rn: feat(rules|j2lint)'
        - 'rn: feat(rules|cli)'
        - 'rn: feat(j2lint|cli|rules)'
        - 'rn: feat(j2lint|rules|cli)'
        - 'rn: feat(cli|j2lint|rules)'
        - 'rn: feat(cli|rules|j2lint)'
        - 'rn: feat(rules|j2lint|cli)'
        - 'rn: feat(rules|cli|j2lint)'
        - 'rn: feat'
    - title: 'Fixed issues'
      labels:
        - 'rn: fix(j2lint)'
        - 'rn: fix(cli)'
        - 'rn: fix(rules)'
        - 'rn: fix(j2lint|cli)'
        - 'rn: fix(j2lint|rules)'
        - 'rn: fix(cli|j2lint)'
        - 'rn: fix(cli|rules)'
        - 'rn: fix(rules|j2lint)'
        - 'rn: fix(rules|cli)'
        - 'rn: fix(j2lint|cli|rules)'
        - 'rn: fix(j2lint|rules|cli)'
        - 'rn: fix(cli|j2lint|rules)'
        - 'rn: fix(cli|rules|j2lint)'
        - 'rn: fix(rules|j2lint|cli)'
        - 'rn: fix(rules|cli|j2lint)'
        - 'rn: fix'
    - title: 'Documentation'
      labels:
        - 'rn: doc(j2lint)'
        - 'rn: doc(cli)'
        - 'rn: doc(rules)'
        - 'rn: doc(j2lint|cli)'
        - 'rn: doc(j2lint|rules)'
        - 'rn: doc(cli|j2lint)'
        - 'rn: doc(cli|rules)'
        - 'rn: doc(rules|j2lint)'
        - 'rn: doc(rules|cli)'
        - 'rn: doc(j2lint|cli|rules)'
        - 'rn: doc(j2lint|rules|cli)'
        - 'rn: doc(cli|j2lint|rules)'
        - 'rn: doc(cli|rules|j2lint)'
        - 'rn: doc(rules|j2lint|cli)'
        - 'rn: doc(rules|cli|j2lint)'
        - 'rn: doc'
    - title: 'Other Changes'
      labels:
        - '*'
