sonar.projectKey=aristanetworks_j2lint
sonar.organization=aristanetworks-1

# Path to sources
sonar.sources=j2lint/

# Exclude asynceapi unused modules for now
# sonar.exclusions=
#sonar.inclusions=

# Path to tests
sonar.tests=tests/
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Python version (for python projects only)
sonar.python.version=3.9,3.10,3.11,3.12,3.13

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=,

sonar.python.coverage.reportPaths=.coverage.xml
