# Copyright (c) 2021-2026 Arista Networks, Inc.
# Use of this source code is governed by the MIT license
# that can be found in the LICENSE file.
"""jinja_template_single_statement_rule.py - Rule class to check if only a single jinja statement is present on each line."""

from __future__ import annotations

from j2lint.linter.error import LinterError
from j2lint.linter.rule import Rule
from j2lint.utils import get_jinja_statements


class JinjaTemplateSingleStatementRule(Rule):
    """Rule class to check if only a single jinja statement is present on each line."""

    rule_id = "S7"
    description = "Jinja statements should be on separate lines, ignoring raw block contents"
    short_description = "single-statement-per-line"
    severity = "MEDIUM"

    def __init__(self, ignore: bool = False, warn: list[Rule] | None = None) -> None:
        super().__init__(ignore=ignore, warn=warn)

    def checktext(self, filename: str, text: str) -> list[LinterError]:
        """Not Implemented for this rule."""
        raise NotImplementedError

    def checkline(self, filename: str, line: str, line_no: int) -> list[LinterError]:
        """Check if the given line matches the error regex.

        Parameters
        ----------
        filename
            The filename to which the line belongs.
        line
            The content of the line to check.
        line_no:
            The line number.

        Returns
        -------
        list[LinterError]
            The list of LinterError generated by this rule.
        """
        statement_count = 0
        raw_block_count = 0

        for statement in get_jinja_statements(line):
            words = statement[0].split()
            if not words:
                continue

            tag = words[0]
            if tag == "raw":
                raw_block_count += 1
                statement_count += 1
                continue

            if tag == "endraw" and raw_block_count > 0:
                raw_block_count -= 1
                continue

            statement_count += 1

        return [LinterError(line_no, line, filename, self)] if statement_count > 1 else []
