---
name: Publish coverage to CodeCov
on:
  workflow_call:
jobs:
  codecov:
    name: Upload to CodeCov.
    if: github.repository == 'aristanetworks/j2lint'
    runs-on: ubuntu-latest
    # These permissions are mandatory for OIDC to work
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Download coverage from unit tests
        continue-on-error: true
        uses: actions/download-artifact@v8
        with:
          name: pytest-coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad
        with:
          use_oidc: true
          fail_ci_if_error: true
